name: Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  pg_tap_tests:
    name: PGTap Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Start Supabase and Run Tests
        run: |
          supabase start
          supabase db reset --yes
          supabase test db
