name: Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  pg_tap_tests:
    name: PGTap Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Supabase Start
        run: supabase db start

      - name: Reset database (apply migrations)
        run: supabase db reset --yes

      - name: Setup supabase testing
        run: |
          psql -v ON_ERROR_STOP=1 -U postgres -d postgres -h localhost -p 54322 -f .github/workflows/tests.sql
        env:
          PGPASSWORD: postgres

      - name: Run Tests
        run: supabase test db
